# Generated by Django 5.1.6 on 2025-02-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_projectmaterial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='quiz',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
