# Generated by Django 5.1.6 on 2025-02-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_assessment_difficulty_alter_assessment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='attempts',
        ),
        migrations.AddField(
            model_name='assessment',
            name='attempts',
            field=models.ManyToManyField(to='app.attempt'),
        ),
    ]
