# Generated by Django 5.1.6 on 2025-02-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_assessment_attempts_assessment_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='attempts',
            field=models.ManyToManyField(blank=True, to='app.attempt'),
        ),
    ]
