# Generated by Django 5.1.6 on 2025-02-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_assessment_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
