# Generated by Django 5.1.6 on 2025-02-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_attempt_timestamp_alter_attempt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='lastAttempt',
        ),
    ]
