# Generated by Django 5.1.6 on 2025-03-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_assessment_lastattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='time_taken',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
