# Generated by Django 5.1.6 on 2025-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_attempt_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='negative_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='partial_credits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='proctor_meta',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='proctored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='timed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='total_duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
