# Generated by Django 5.1.7 on 2025-03-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_attempt_negative_score_attempt_partial_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaterial',
            name='important_tokens',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
