# Generated by Django 5.1.7 on 2025-03-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_projectmaterial_important_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaterial',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
