# Generated by Django 5.1.7 on 2025-03-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_projectmaterial_parsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaterial',
            name='parsed',
            field=models.CharField(max_length=30),
        ),
    ]
