# Generated by Django 5.1.7 on 2025-03-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_projectmaterial_parsed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmaterial',
            old_name='parsed',
            new_name='status',
        ),
    ]
