# Generated by Django 5.1.7 on 2025-03-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_parsed_projectmaterial_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmaterial',
            name='status',
        ),
    ]
