# Generated by Django 5.1.7 on 2025-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_projectmaterial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='ek',
            field=models.TextField(blank=True, null=True),
        ),
    ]
