# Generated by Django 5.1.7 on 2025-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_attempt_ek'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='ek',
            field=models.TextField(blank=True, null=True),
        ),
    ]
