# Generated by Django 5.1.7 on 2025-03-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_assessment_ek'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
