# Generated by Django 5.1.7 on 2025-04-09 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_attempt_end_time_attempt_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
